name: Run pymm

on:
 push:
   branches:
     - main
 pull_request:
   
jobs:
  run-pymm-local:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.14
      uses: actions/setup-python@v2
      with:
        python-version: 3.14

    - name: Install OpenFOAM
      run: |
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key > /etc/apt/trusted.gpg.d/openfoam.asc"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
        sudo apt-get update
        sudo apt -y install openfoam13
    
    - name: Install gmsh
      run: |
        sudo apt-get update
        sudo apt-get -y install gmsh
        
    - name: Install test dependecies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r dev-requirements.txt
      
    - name: Install pymm
      run: |
        pip install .

    - name: Check code style and linting 
      run: |
        black --target-version py312 --check src/ tests/
        pylint src/ tests/
        ruff check src/ tests/
        mypy --ignore-missing-imports src/ tests/
      
    - name: Run the tests
      run: |
        set +e
        source /opt/openfoam13/etc/bashrc
        set -e
        pytest --cov=pymm --exitfirst --cov-report term-missing --basetemp=test_outputs tests/

    - name: Build documentation
      run: |
        pushd docs
        make html
